version: "3.8"
services:
  app:
    image: nhan2804/vncdc-duplicator:v1.0.0
    networks:
      - web
    build:
      context: ./
      dockerfile: Dockerfile
    # deploy:
    #   placement:
    #     constraints:
    #       - node.role == manager
    volumes:
      # - ./nginx:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
    # - ./certbot/www:/var/www/certbot
  nginx:
    image: nginx:1.24.0-alpine
    networks:
      - web
    volumes:
      - ./nginx:/etc/nginx/conf.d
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
networks:
  web:
